import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { FC, PropsWithChildren } from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

const Layout: FC<PropsWithChildren> = ({ children }): JSX.Element => {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default Layout;
